image:
  file: .cde.Dockerfile

tasks:
  - name: Versions
    command: |
      sh ./tools_platform/environment_versions.sh
  - name: Variables
    command: |
      sh ./tools_platform/environment_variables.sh
  - name: Azure CLI
    command: |
      sh ./tools_platform/azure_login_service_principle.sh
      gp sync-done waitonazurecli
  - name: Azure Storage
    command: |
      gp sync-await waitonazurecli
      sh ./tools_platform/infrastructure_state_storage.sh
      gp sync-done waitonnstate
  - name: Terraform
    command: |
      gp sync-await waitonnstate
      sh ./tools_platform/infrastructure.sh

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-azureresourcegroups
    - formulahendry.code-runner
