image:
  file: .cde.Dockerfile

tasks:
  - name: Versions
    command: |
      sh ./tools_platform/environment_versions.sh
  - name: Variables
    command: |
      sh ./tools_platform/environment_variables.sh
  - name: Azure CLI
    command: |
      sh ./tools_platform/azure_login_service_principle.sh
      gp sync-done wait_on_azure_cli
  - name: Azure Storage
    command: |
      gp sync-await wait_on_azure_cli
      sh ./tools_platform/infrastructure_state_storage.sh
      gp sync-done wait_on_state
  - name: Domain Registration Platform
    command: |
      gp sync-await wait_on_state
      sh ./tools_platform/infrastructure.sh domain_registration False
  - name: Application Platform
    command: |
      gp sync-await wait_on_state
      sh ./tools_platform/infrastructure.sh application_platform False
  - name: Data Analytics
    command: |
      gp sync-await wait_on_state
      sh ./tools_platform/infrastructure.sh data_analytics False

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-azureresourcegroups
    - ms-vscode.vscode-node-azure-pack
    - formulahendry.code-runner
    - github.vscode-github-actions
    - gitpod.gitpod-desktop
    - redhat.vscode-yaml
